### ISSUE TITLE
--extended_details result in http: panic 

### ISSUE THREAD

**Issue by ionics** [DRuggeri/alertmanager_gotify_bridge#11]
Hi folks,

--extended_details result in http: panic  serving 127.0.0.1:57432: assignment to entry in nil map

Command:

`alertmanager_gotify_bridge --gotify_endpoint="http://127.0.0.1:9099/message" --bind_address=0.0.0.0 --port=8080 --webhook_path="/gotify_webhook" --timeout=2s --title_annotation="summary" --message_annotation="description" --priority_annotation="priority" --default_priority=5 --metrics_namespace="alertmanager_gotify_bridge" --metrics_path="/metrics" --extended_details --debug`

Error:

```
2021/08/03 16:44:53 Detected 1 alerts
2021/08/03 16:44:53   Alert 0
2021/08/03 16:44:53     title: [FIR] High latency is high!
2021/08/03 16:44:53     message: This is a bad systembug...
2021/08/03 16:44:53     priority: 10
2021/08/03 16:44:53 http: panic serving 127.0.0.1:57432: assignment to entry in nil map
goroutine 26 [running]:
net/http.(*conn).serve.func1(0xc000232780)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x8f1820, 0xa2b950)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
main.(*bridge).handleCall(0xc00023c1e0, 0xa3d3e0, 0xc0002487e0, 0xc000216b00)
	/home/hax/go/src/github.com/DRuggeri/alertmanager_gotify_bridge/main.go:307 +0x1a29
net/http.HandlerFunc.ServeHTTP(0xc00021a460, 0xa3d3e0, 0xc0002487e0, 0xc000216b00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00022c2c0, 0xa3d3e0, 0xc0002487e0, 0xc000216b00)
	/usr/local/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000248000, 0xa3d3e0, 0xc0002487e0, 0xc000216b00)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000232780, 0xa3e8e0, 0xc00022ca00)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
```

**Comment by ionics** [comment]
Error seems on line 307 in main.go Version 0.5.1:
~line 307:		extrasNotification["click"]["url"] = alert.GeneratorURL

**Comment by DRuggeri** [comment]
Hey there, @ionics - thanks for the report. Yeah, I can see the issue there. I've fixed it in the main branch and will cut a release soon.
